// English word -> Hebrew translation, with an optional emoji for a non-reading
// visual cue, and a tier (1-60) used to place the word in the age/sub-level
// curriculum (tier 1-5 = age 3, 6-10 = age 4, ... 56-60 = age 14).
window.WORDS = [
  // tier 1
  { en: "red", he: "אדום", emoji: "🔴", tier: 1 },
  { en: "blue", he: "כחול", emoji: "🔵", tier: 1 },
  { en: "green", he: "ירוק", emoji: "🟢", tier: 1 },
  { en: "yellow", he: "צהוב", emoji: "🟡", tier: 1 },
  { en: "orange", he: "כתום", emoji: "🟠", tier: 1 },
  { en: "purple", he: "סגול", emoji: "🟣", tier: 1 },
  { en: "pink", he: "ורוד", emoji: "💗", tier: 1 },
  { en: "black", he: "שחור", emoji: "⚫", tier: 1 },
  { en: "white", he: "לבן", emoji: "⚪", tier: 1 },
  { en: "brown", he: "חום", emoji: "🟤", tier: 1 },
  // tier 2
  { en: "dog", he: "כלב", emoji: "🐶", tier: 2 },
  { en: "cat", he: "חתול", emoji: "🐱", tier: 2 },
  { en: "fish", he: "דג", emoji: "🐟", tier: 2 },
  { en: "bird", he: "ציפור", emoji: "🐦", tier: 2 },
  { en: "cow", he: "פרה", emoji: "🐮", tier: 2 },
  { en: "pig", he: "חזיר", emoji: "🐷", tier: 2 },
  { en: "duck", he: "ברווז", emoji: "🦆", tier: 2 },
  { en: "frog", he: "צפרדע", emoji: "🐸", tier: 2 },
  { en: "bear", he: "דוב", emoji: "🐻", tier: 2 },
  { en: "mouse", he: "עכבר", emoji: "🐭", tier: 2 },
  // tier 3
  { en: "mom", he: "אמא", emoji: "👩", tier: 3 },
  { en: "dad", he: "אבא", emoji: "👨", tier: 3 },
  { en: "baby", he: "תינוק", emoji: "👶", tier: 3 },
  { en: "sister", he: "אחות", emoji: "👧", tier: 3 },
  { en: "brother", he: "אח", emoji: "👦", tier: 3 },
  { en: "grandma", he: "סבתא", emoji: "👵", tier: 3 },
  { en: "grandpa", he: "סבא", emoji: "👴", tier: 3 },
  { en: "friend", he: "חבר", emoji: "🧑", tier: 3 },
  { en: "boy", he: "ילד", emoji: "👦", tier: 3 },
  { en: "girl", he: "ילדה", emoji: "👧", tier: 3 },
  // tier 4
  { en: "apple", he: "תפוח", emoji: "🍎", tier: 4 },
  { en: "banana", he: "בננה", emoji: "🍌", tier: 4 },
  { en: "milk", he: "חלב", emoji: "🥛", tier: 4 },
  { en: "bread", he: "לחם", emoji: "🍞", tier: 4 },
  { en: "egg", he: "ביצה", emoji: "🥚", tier: 4 },
  { en: "water", he: "מים", emoji: "💧", tier: 4 },
  { en: "juice", he: "מיץ", emoji: "🧃", tier: 4 },
  { en: "cookie", he: "עוגייה", emoji: "🍪", tier: 4 },
  { en: "cake", he: "עוגה", emoji: "🎂", tier: 4 },
  { en: "cheese", he: "גבינה", emoji: "🧀", tier: 4 },
  { en: "carrot", he: "גזר", emoji: "🥕", tier: 4 },
  { en: "grapes", he: "ענבים", emoji: "🍇", tier: 4 },
  { en: "strawberry", he: "תות", emoji: "🍓", tier: 4 },
  { en: "watermelon", he: "אבטיח", emoji: "🍉", tier: 4 },
  { en: "ice cream", he: "גלידה", emoji: "🍦", tier: 4 },
  { en: "pizza", he: "פיצה", emoji: "🍕", tier: 4 },
  // tier 5
  { en: "hand", he: "יד", emoji: "✋", tier: 5 },
  { en: "foot", he: "כף רגל", emoji: "🦶", tier: 5 },
  { en: "eye", he: "עין", emoji: "👁️", tier: 5 },
  { en: "ear", he: "אוזן", emoji: null, tier: 5 },
  { en: "nose", he: "אף", emoji: null, tier: 5 },
  { en: "mouth", he: "פה", emoji: null, tier: 5 },
  { en: "head", he: "ראש", emoji: null, tier: 5 },
  { en: "hair", he: "שיער", emoji: null, tier: 5 },
  { en: "arm", he: "זרוע", emoji: null, tier: 5 },
  { en: "leg", he: "רגל", emoji: null, tier: 5 },
  // tier 6
  { en: "lion", he: "אריה", emoji: "🦁", tier: 6 },
  { en: "elephant", he: "פיל", emoji: "🐘", tier: 6 },
  { en: "monkey", he: "קוף", emoji: "🐵", tier: 6 },
  { en: "horse", he: "סוס", emoji: "🐴", tier: 6 },
  { en: "rabbit", he: "ארנב", emoji: "🐰", tier: 6 },
  { en: "sheep", he: "כבשה", emoji: "🐑", tier: 6 },
  { en: "chicken", he: "תרנגולת", emoji: "🐔", tier: 6 },
  { en: "snake", he: "נחש", emoji: "🐍", tier: 6 },
  { en: "turtle", he: "צב", emoji: "🐢", tier: 6 },
  { en: "bee", he: "דבורה", emoji: "🐝", tier: 6 },
  // tier 7
  { en: "ball", he: "כדור", emoji: "⚽", tier: 7 },
  { en: "doll", he: "בובה", emoji: null, tier: 7 },
  { en: "book", he: "ספר", emoji: "📖", tier: 7 },
  { en: "box", he: "קופסה", emoji: "📦", tier: 7 },
  { en: "bag", he: "תיק", emoji: "🎒", tier: 7 },
  { en: "key", he: "מפתח", emoji: "🔑", tier: 7 },
  { en: "clock", he: "שעון", emoji: "🕐", tier: 7 },
  { en: "chair", he: "כיסא", emoji: "🪑", tier: 7 },
  { en: "table", he: "שולחן", emoji: null, tier: 7 },
  { en: "door", he: "דלת", emoji: "🚪", tier: 7 },
  { en: "balloon", he: "בלון", emoji: "🎈", tier: 7 },
  // tier 8
  { en: "hat", he: "כובע", emoji: "🎩", tier: 8 },
  { en: "shirt", he: "חולצה", emoji: "👕", tier: 8 },
  { en: "shoe", he: "נעל", emoji: "👟", tier: 8 },
  { en: "sock", he: "גרב", emoji: "🧦", tier: 8 },
  { en: "coat", he: "מעיל", emoji: "🧥", tier: 8 },
  { en: "dress", he: "שמלה", emoji: "👗", tier: 8 },
  { en: "pants", he: "מכנסיים", emoji: null, tier: 8 },
  { en: "glove", he: "כפפה", emoji: "🧤", tier: 8 },
  { en: "scarf", he: "צעיף", emoji: "🧣", tier: 8 },
  { en: "belt", he: "חגורה", emoji: null, tier: 8 },
  // tier 9
  { en: "sun", he: "שמש", emoji: "☀️", tier: 9 },
  { en: "moon", he: "ירח", emoji: "🌙", tier: 9 },
  { en: "star", he: "כוכב", emoji: "⭐", tier: 9 },
  { en: "rain", he: "גשם", emoji: "🌧️", tier: 9 },
  { en: "cloud", he: "עננה", emoji: "☁️", tier: 9 },
  { en: "tree", he: "עץ", emoji: "🌳", tier: 9 },
  { en: "flower", he: "פרח", emoji: "🌸", tier: 9 },
  { en: "grass", he: "דשא", emoji: "🌱", tier: 9 },
  { en: "snow", he: "שלג", emoji: "❄️", tier: 9 },
  { en: "wind", he: "רוח", emoji: "💨", tier: 9 },
  { en: "umbrella", he: "מטריה", emoji: "☂️", tier: 9 },
  // tier 10
  { en: "happy", he: "שמח", emoji: "😊", tier: 10 },
  { en: "sad", he: "עצוב", emoji: "😢", tier: 10 },
  { en: "angry", he: "כועס", emoji: "😠", tier: 10 },
  { en: "scared", he: "מפוחד", emoji: "😨", tier: 10 },
  { en: "tired", he: "עייף", emoji: "😴", tier: 10 },
  { en: "hungry", he: "רעב", emoji: null, tier: 10 },
  { en: "thirsty", he: "צמא", emoji: null, tier: 10 },
  { en: "sick", he: "חולה", emoji: "🤒", tier: 10 },
  { en: "sleepy", he: "מנומנם", emoji: null, tier: 10 },
  { en: "excited", he: "נרגש", emoji: null, tier: 10 },
  // tier 11
  { en: "circle", he: "עיגול", emoji: "⭕", tier: 11 },
  { en: "square", he: "ריבוע", emoji: "🟦", tier: 11 },
  { en: "triangle", he: "משולש", emoji: "🔺", tier: 11 },
  { en: "rectangle", he: "מלבן", emoji: null, tier: 11 },
  { en: "oval", he: "אליפסה", emoji: null, tier: 11 },
  { en: "diamond", he: "יהלום", emoji: "💎", tier: 11 },
  { en: "heart", he: "לב", emoji: "❤️", tier: 11 },
  { en: "line", he: "קו", emoji: null, tier: 11 },
  { en: "dot", he: "נקודה", emoji: null, tier: 11 },
  { en: "cube", he: "קובייה", emoji: null, tier: 11 },
  // tier 12
  { en: "one", he: "אחת", emoji: null, tier: 12 },
  { en: "two", he: "שתיים", emoji: null, tier: 12 },
  { en: "three", he: "שלוש", emoji: null, tier: 12 },
  { en: "four", he: "ארבע", emoji: null, tier: 12 },
  { en: "five", he: "חמש", emoji: null, tier: 12 },
  { en: "six", he: "שש", emoji: null, tier: 12 },
  { en: "seven", he: "שבע", emoji: null, tier: 12 },
  { en: "eight", he: "שמונה", emoji: null, tier: 12 },
  { en: "nine", he: "תשע", emoji: null, tier: 12 },
  { en: "ten", he: "עשר", emoji: null, tier: 12 },
  { en: "zero", he: "אפס", emoji: null, tier: 12 },
  { en: "first", he: "ראשון", emoji: null, tier: 12 },
  { en: "last", he: "אחרון", emoji: null, tier: 12 },
  // tier 13
  { en: "bus", he: "אוטובוס", emoji: "🚌", tier: 13 },
  { en: "train", he: "רכבת", emoji: "🚂", tier: 13 },
  { en: "truck", he: "משאית", emoji: "🚚", tier: 13 },
  { en: "ship", he: "אונייה", emoji: "🚢", tier: 13 },
  { en: "helicopter", he: "מסוק", emoji: "🚁", tier: 13 },
  { en: "rocket", he: "רקטה", emoji: "🚀", tier: 13 },
  { en: "motorcycle", he: "אופנוע", emoji: "🏍️", tier: 13 },
  { en: "taxi", he: "מונית", emoji: "🚕", tier: 13 },
  { en: "subway", he: "רכבת תחתית", emoji: null, tier: 13 },
  { en: "scooter", he: "קורקינט", emoji: null, tier: 13 },
  { en: "car", he: "מכונית", emoji: "🚗", tier: 13 },
  { en: "bicycle", he: "אופניים", emoji: "🚲", tier: 13 },
  { en: "boat", he: "סירה", emoji: "⛵", tier: 13 },
  { en: "airplane", he: "מטוס", emoji: "✈️", tier: 13 },
  // tier 14
  { en: "spoon", he: "כף", emoji: "🥄", tier: 14 },
  { en: "fork", he: "מזלג", emoji: "🍴", tier: 14 },
  { en: "knife", he: "סכין", emoji: "🔪", tier: 14 },
  { en: "plate", he: "צלחת", emoji: "🍽️", tier: 14 },
  { en: "cup", he: "כוס", emoji: "🥤", tier: 14 },
  { en: "pot", he: "סיר", emoji: null, tier: 14 },
  { en: "pan", he: "מחבת", emoji: null, tier: 14 },
  { en: "oven", he: "תנור", emoji: null, tier: 14 },
  { en: "fridge", he: "מקרר", emoji: null, tier: 14 },
  { en: "sink", he: "כיור", emoji: null, tier: 14 },
  // tier 15
  { en: "bathroom", he: "חדר אמבטיה", emoji: "🛁", tier: 15 },
  { en: "bedroom", he: "חדר שינה", emoji: "🛏️", tier: 15 },
  { en: "kitchen", he: "מטבח", emoji: null, tier: 15 },
  { en: "soap", he: "סבון", emoji: "🧼", tier: 15 },
  { en: "towel", he: "מגבת", emoji: null, tier: 15 },
  { en: "toothbrush", he: "מברשת שיניים", emoji: "🪥", tier: 15 },
  { en: "mirror", he: "מראה", emoji: "🪞", tier: 15 },
  { en: "bathtub", he: "אמבטיה", emoji: null, tier: 15 },
  { en: "shower", he: "מקלחת", emoji: "🚿", tier: 15 },
  { en: "toilet", he: "אסלה", emoji: "🚽", tier: 15 },
  { en: "house", he: "בית", emoji: "🏠", tier: 15 },
  // tier 16
  { en: "run", he: "לרוץ", emoji: "🏃", tier: 16 },
  { en: "jump", he: "לקפוץ", emoji: null, tier: 16 },
  { en: "walk", he: "ללכת", emoji: "🚶", tier: 16 },
  { en: "eat", he: "לאכול", emoji: "🍽️", tier: 16 },
  { en: "drink", he: "לשתות", emoji: null, tier: 16 },
  { en: "sleep", he: "לישון", emoji: "😴", tier: 16 },
  { en: "sing", he: "לשיר", emoji: "🎤", tier: 16 },
  { en: "dance", he: "לרקוד", emoji: "💃", tier: 16 },
  { en: "read", he: "לקרוא", emoji: "📖", tier: 16 },
  { en: "write", he: "לכתוב", emoji: "✍️", tier: 16 },
  // tier 17
  { en: "sunday", he: "יום ראשון", emoji: null, tier: 17 },
  { en: "monday", he: "יום שני", emoji: null, tier: 17 },
  { en: "tuesday", he: "יום שלישי", emoji: null, tier: 17 },
  { en: "wednesday", he: "יום רביעי", emoji: null, tier: 17 },
  { en: "thursday", he: "יום חמישי", emoji: null, tier: 17 },
  { en: "friday", he: "יום שישי", emoji: null, tier: 17 },
  { en: "saturday", he: "שבת", emoji: null, tier: 17 },
  { en: "today", he: "היום", emoji: null, tier: 17 },
  { en: "tomorrow", he: "מחר", emoji: null, tier: 17 },
  { en: "yesterday", he: "אתמול", emoji: null, tier: 17 },
  // tier 18
  { en: "soccer", he: "כדורגל", emoji: "⚽", tier: 18 },
  { en: "basketball", he: "כדורסל", emoji: "🏀", tier: 18 },
  { en: "baseball", he: "בייסבול", emoji: "⚾", tier: 18 },
  { en: "tennis", he: "טניס", emoji: "🎾", tier: 18 },
  { en: "swimming", he: "שחייה", emoji: "🏊", tier: 18 },
  { en: "running", he: "ריצה", emoji: null, tier: 18 },
  { en: "football", he: "פוטבול", emoji: "🏈", tier: 18 },
  { en: "volleyball", he: "כדורעף", emoji: "🏐", tier: 18 },
  { en: "skating", he: "החלקה", emoji: "⛸️", tier: 18 },
  { en: "biking", he: "רכיבה על אופניים", emoji: null, tier: 18 },
  // tier 19
  { en: "big", he: "גדול", emoji: null, tier: 19 },
  { en: "small", he: "קטן", emoji: null, tier: 19 },
  { en: "fast", he: "מהיר", emoji: null, tier: 19 },
  { en: "slow", he: "לאט", emoji: null, tier: 19 },
  { en: "hot", he: "חם", emoji: null, tier: 19 },
  { en: "cold", he: "קר", emoji: null, tier: 19 },
  { en: "tall", he: "גבוה", emoji: null, tier: 19 },
  { en: "short", he: "קצר", emoji: null, tier: 19 },
  { en: "heavy", he: "כבד", emoji: null, tier: 19 },
  { en: "light", he: "קל", emoji: null, tier: 19 },
  // tier 20
  { en: "pencil", he: "עיפרון", emoji: "✏️", tier: 20 },
  { en: "eraser", he: "מחק", emoji: null, tier: 20 },
  { en: "ruler", he: "סרגל", emoji: "📏", tier: 20 },
  { en: "backpack", he: "תיק גב", emoji: "🎒", tier: 20 },
  { en: "desk", he: "שולחן כתיבה", emoji: null, tier: 20 },
  { en: "teacher", he: "מורה", emoji: "🧑‍🏫", tier: 20 },
  { en: "student", he: "תלמיד", emoji: null, tier: 20 },
  { en: "classroom", he: "כיתה", emoji: null, tier: 20 },
  { en: "homework", he: "שיעורי בית", emoji: null, tier: 20 },
  { en: "notebook", he: "מחברת", emoji: "📓", tier: 20 },
  // tier 21
  { en: "hour", he: "שעה", emoji: null, tier: 21 },
  { en: "minute", he: "דקה", emoji: null, tier: 21 },
  { en: "second", he: "שנייה", emoji: null, tier: 21 },
  { en: "morning", he: "בוקר", emoji: "🌅", tier: 21 },
  { en: "afternoon", he: "צהריים", emoji: null, tier: 21 },
  { en: "evening", he: "ערב", emoji: "🌆", tier: 21 },
  { en: "night", he: "לילה", emoji: "🌃", tier: 21 },
  { en: "week", he: "שבוע", emoji: null, tier: 21 },
  { en: "month", he: "חודש", emoji: null, tier: 21 },
  { en: "year", he: "שנה", emoji: null, tier: 21 },
  // tier 22
  { en: "doctor", he: "רופא", emoji: "🩺", tier: 22 },
  { en: "nurse", he: "אחות", emoji: "👩‍⚕️", tier: 22 },
  { en: "firefighter", he: "כבאי", emoji: "🧑‍🚒", tier: 22 },
  { en: "police", he: "שוטר", emoji: "👮", tier: 22 },
  { en: "farmer", he: "חוואי", emoji: "🧑‍🌾", tier: 22 },
  { en: "chef", he: "שף", emoji: "👨‍🍳", tier: 22 },
  { en: "pilot", he: "טייס", emoji: "🧑‍✈️", tier: 22 },
  { en: "dentist", he: "רופא שיניים", emoji: null, tier: 22 },
  { en: "artist", he: "אמן", emoji: "🎨", tier: 22 },
  { en: "singer", he: "זמר", emoji: "🎤", tier: 22 },
  // tier 23
  { en: "park", he: "פארק", emoji: "🏞️", tier: 23 },
  { en: "library", he: "ספרייה", emoji: null, tier: 23 },
  { en: "hospital", he: "בית חולים", emoji: "🏥", tier: 23 },
  { en: "store", he: "חנות", emoji: "🏬", tier: 23 },
  { en: "restaurant", he: "מסעדה", emoji: "🍽️", tier: 23 },
  { en: "zoo", he: "גן חיות", emoji: null, tier: 23 },
  { en: "museum", he: "מוזיאון", emoji: "🏛️", tier: 23 },
  { en: "playground", he: "מגרש משחקים", emoji: null, tier: 23 },
  { en: "market", he: "שוק", emoji: null, tier: 23 },
  { en: "bakery", he: "מאפייה", emoji: null, tier: 23 },
  { en: "school", he: "בית ספר", emoji: "🏫", tier: 23 },
  // tier 24
  { en: "cook", he: "לבשל", emoji: "🍳", tier: 24 },
  { en: "clean", he: "לנקות", emoji: null, tier: 24 },
  { en: "wash", he: "לשטוף", emoji: null, tier: 24 },
  { en: "build", he: "לבנות", emoji: "🏗️", tier: 24 },
  { en: "draw", he: "לצייר", emoji: "🎨", tier: 24 },
  { en: "paint", he: "לצבוע", emoji: null, tier: 24 },
  { en: "climb", he: "לטפס", emoji: "🧗", tier: 24 },
  { en: "throw", he: "לזרוק", emoji: null, tier: 24 },
  { en: "catch", he: "לתפוס", emoji: null, tier: 24 },
  { en: "kick", he: "לבעוט", emoji: null, tier: 24 },
  // tier 25
  { en: "beautiful", he: "יפה", emoji: null, tier: 25 },
  { en: "ugly", he: "מכוער", emoji: null, tier: 25 },
  { en: "strong", he: "חזק", emoji: "💪", tier: 25 },
  { en: "weak", he: "חלש", emoji: null, tier: 25 },
  { en: "tidy", he: "מסודר", emoji: null, tier: 25 },
  { en: "dirty", he: "מלוכלך", emoji: null, tier: 25 },
  { en: "easy", he: "קל", emoji: null, tier: 25 },
  { en: "difficult", he: "קשה", emoji: null, tier: 25 },
  { en: "expensive", he: "יקר", emoji: null, tier: 25 },
  { en: "cheap", he: "זול", emoji: null, tier: 25 },
  // tier 26
  { en: "rock", he: "סלע", emoji: "🪨", tier: 26 },
  { en: "mountain", he: "הר", emoji: "⛰️", tier: 26 },
  { en: "river", he: "נהר", emoji: null, tier: 26 },
  { en: "ocean", he: "אוקיינוס", emoji: "🌊", tier: 26 },
  { en: "forest", he: "יער", emoji: "🌲", tier: 26 },
  { en: "desert", he: "מדבר", emoji: null, tier: 26 },
  { en: "island", he: "אי", emoji: "🏝️", tier: 26 },
  { en: "volcano", he: "הר געש", emoji: "🌋", tier: 26 },
  { en: "cave", he: "מערה", emoji: null, tier: 26 },
  { en: "waterfall", he: "מפל מים", emoji: null, tier: 26 },
  // tier 27
  { en: "hammer", he: "פטיש", emoji: "🔨", tier: 27 },
  { en: "screwdriver", he: "מברג", emoji: null, tier: 27 },
  { en: "saw", he: "מסור", emoji: null, tier: 27 },
  { en: "drill", he: "מקדחה", emoji: null, tier: 27 },
  { en: "ladder", he: "סולם", emoji: "🪜", tier: 27 },
  { en: "wrench", he: "מפתח ברגים", emoji: "🔧", tier: 27 },
  { en: "nail", he: "מסמר", emoji: null, tier: 27 },
  { en: "screw", he: "בורג", emoji: null, tier: 27 },
  { en: "tape", he: "נייר דבק", emoji: null, tier: 27 },
  { en: "glue", he: "דבק", emoji: null, tier: 27 },
  // tier 28
  { en: "up", he: "מעלה", emoji: null, tier: 28 },
  { en: "down", he: "מטה", emoji: null, tier: 28 },
  { en: "left", he: "שמאלה", emoji: null, tier: 28 },
  { en: "right", he: "ימינה", emoji: null, tier: 28 },
  { en: "inside", he: "בפנים", emoji: null, tier: 28 },
  { en: "outside", he: "בחוץ", emoji: null, tier: 28 },
  { en: "between", he: "בין", emoji: null, tier: 28 },
  { en: "behind", he: "מאחורי", emoji: null, tier: 28 },
  { en: "front", he: "לפני", emoji: null, tier: 28 },
  { en: "under", he: "מתחת", emoji: null, tier: 28 },
  // tier 29
  { en: "spring", he: "אביב", emoji: "🌷", tier: 29 },
  { en: "summer", he: "קיץ", emoji: "☀️", tier: 29 },
  { en: "autumn", he: "סתיו", emoji: "🍂", tier: 29 },
  { en: "winter", he: "חורף", emoji: "❄️", tier: 29 },
  { en: "storm", he: "סופה", emoji: "⛈️", tier: 29 },
  { en: "thunder", he: "רעם", emoji: null, tier: 29 },
  { en: "lightning", he: "ברק", emoji: "⚡", tier: 29 },
  { en: "fog", he: "ערפל", emoji: "🌫️", tier: 29 },
  { en: "humidity", he: "לחות", emoji: null, tier: 29 },
  { en: "temperature", he: "טמפרטורה", emoji: null, tier: 29 },
  // tier 30
  { en: "bridge", he: "גשר", emoji: "🌉", tier: 30 },
  { en: "tower", he: "מגדל", emoji: "🗼", tier: 30 },
  { en: "castle", he: "טירה", emoji: "🏰", tier: 30 },
  { en: "tunnel", he: "מנהרה", emoji: null, tier: 30 },
  { en: "harbor", he: "נמל", emoji: null, tier: 30 },
  { en: "airport", he: "שדה תעופה", emoji: "🛫", tier: 30 },
  { en: "station", he: "תחנה", emoji: null, tier: 30 },
  { en: "factory", he: "מפעל", emoji: "🏭", tier: 30 },
  { en: "farm", he: "חווה", emoji: null, tier: 30 },
  { en: "village", he: "כפר", emoji: null, tier: 30 },
  // tier 31
  { en: "kidney", he: "כליה", emoji: null, tier: 31 },
  { en: "brain", he: "מוח", emoji: "🧠", tier: 31 },
  { en: "bone", he: "עצם", emoji: null, tier: 31 },
  { en: "muscle", he: "שריר", emoji: "💪", tier: 31 },
  { en: "blood", he: "דם", emoji: null, tier: 31 },
  { en: "skin", he: "עור", emoji: null, tier: 31 },
  { en: "lung", he: "ריאה", emoji: null, tier: 31 },
  { en: "stomach", he: "בטן", emoji: null, tier: 31 },
  { en: "tooth", he: "שן", emoji: "🦷", tier: 31 },
  { en: "throat", he: "גרון", emoji: null, tier: 31 },
  // tier 32
  { en: "country", he: "מדינה", emoji: null, tier: 32 },
  { en: "city", he: "עיר", emoji: "🏙️", tier: 32 },
  { en: "continent", he: "יבשת", emoji: null, tier: 32 },
  { en: "map", he: "מפה", emoji: "🗺️", tier: 32 },
  { en: "border", he: "גבול", emoji: null, tier: 32 },
  { en: "capital", he: "עיר בירה", emoji: null, tier: 32 },
  { en: "population", he: "אוכלוסייה", emoji: null, tier: 32 },
  { en: "language", he: "שפה", emoji: null, tier: 32 },
  { en: "culture", he: "תרבות", emoji: null, tier: 32 },
  { en: "flag", he: "דגל", emoji: "🚩", tier: 32 },
  // tier 33
  { en: "idea", he: "אידיאה", emoji: "💡", tier: 33 },
  { en: "plan", he: "תוכנית", emoji: null, tier: 33 },
  { en: "problem", he: "בעיה", emoji: null, tier: 33 },
  { en: "solution", he: "פתרון", emoji: null, tier: 33 },
  { en: "reason", he: "סיבה", emoji: null, tier: 33 },
  { en: "example", he: "דוגמה", emoji: null, tier: 33 },
  { en: "choice", he: "בחירה", emoji: null, tier: 33 },
  { en: "chance", he: "סיכוי", emoji: null, tier: 33 },
  { en: "mistake", he: "טעות", emoji: null, tier: 33 },
  { en: "secret", he: "סוד", emoji: "🤫", tier: 33 },
  // tier 34
  { en: "drawing", he: "ציור", emoji: "🎨", tier: 34 },
  { en: "painting", he: "צביעה", emoji: null, tier: 34 },
  { en: "collecting", he: "אספנות", emoji: null, tier: 34 },
  { en: "gardening", he: "גינון", emoji: "🌱", tier: 34 },
  { en: "baking", he: "אפייה", emoji: "🧁", tier: 34 },
  { en: "photography", he: "צילום", emoji: "📷", tier: 34 },
  { en: "chess", he: "שחמט", emoji: "♟️", tier: 34 },
  { en: "puzzle", he: "פאזל", emoji: "🧩", tier: 34 },
  { en: "camping", he: "קמפינג", emoji: "🏕️", tier: 34 },
  { en: "fishing", he: "דיג", emoji: "🎣", tier: 34 },
  // tier 35
  { en: "music", he: "מוזיקה", emoji: "🎵", tier: 35 },
  { en: "song", he: "שיר", emoji: "🎶", tier: 35 },
  { en: "melody", he: "מנגינה", emoji: null, tier: 35 },
  { en: "instrument", he: "כלי נגינה", emoji: null, tier: 35 },
  { en: "guitar", he: "גיטרה", emoji: "🎸", tier: 35 },
  { en: "piano", he: "פסנתר", emoji: "🎹", tier: 35 },
  { en: "drum", he: "תוף", emoji: "🥁", tier: 35 },
  { en: "brush", he: "מברשת", emoji: null, tier: 35 },
  { en: "sculpture", he: "פסל", emoji: null, tier: 35 },
  { en: "rhythm", he: "קצב", emoji: null, tier: 35 },
  // tier 36
  { en: "computer", he: "מחשב", emoji: "💻", tier: 36 },
  { en: "phone", he: "טלפון", emoji: "📱", tier: 36 },
  { en: "internet", he: "אינטרנט", emoji: null, tier: 36 },
  { en: "robot", he: "רובוט", emoji: "🤖", tier: 36 },
  { en: "camera", he: "מצלמה", emoji: "📷", tier: 36 },
  { en: "screen", he: "מסך", emoji: null, tier: 36 },
  { en: "keyboard", he: "מקלדת", emoji: "⌨️", tier: 36 },
  { en: "printer", he: "מדפסת", emoji: null, tier: 36 },
  { en: "battery", he: "סוללה", emoji: "🔋", tier: 36 },
  { en: "password", he: "סיסמה", emoji: null, tier: 36 },
  // tier 37
  { en: "discover", he: "לגלות", emoji: null, tier: 37 },
  { en: "invent", he: "להמציא", emoji: null, tier: 37 },
  { en: "explore", he: "לחקור", emoji: null, tier: 37 },
  { en: "create", he: "ליצור", emoji: null, tier: 37 },
  { en: "design", he: "לתכנן", emoji: null, tier: 37 },
  { en: "improve", he: "לשפר", emoji: null, tier: 37 },
  { en: "develop", he: "לפתח", emoji: null, tier: 37 },
  { en: "achieve", he: "להשיג", emoji: null, tier: 37 },
  { en: "succeed", he: "להצליח", emoji: null, tier: 37 },
  { en: "fail", he: "להיכשל", emoji: null, tier: 37 },
  // tier 38
  { en: "proud", he: "גאה", emoji: null, tier: 38 },
  { en: "jealous", he: "מקנא", emoji: null, tier: 38 },
  { en: "confused", he: "מבולבל", emoji: null, tier: 38 },
  { en: "curious", he: "סקרן", emoji: null, tier: 38 },
  { en: "nervous", he: "עצבני", emoji: null, tier: 38 },
  { en: "confident", he: "בטוח בעצמו", emoji: null, tier: 38 },
  { en: "embarrassed", he: "נבוך", emoji: null, tier: 38 },
  { en: "disappointed", he: "מאוכזב", emoji: null, tier: 38 },
  { en: "grateful", he: "אסיר תודה", emoji: null, tier: 38 },
  { en: "surprised", he: "מופתע", emoji: null, tier: 38 },
  // tier 39
  { en: "energy", he: "אנרגיה", emoji: "⚡", tier: 39 },
  { en: "gravity", he: "כוח משיכה", emoji: null, tier: 39 },
  { en: "magnet", he: "מגנט", emoji: "🧲", tier: 39 },
  { en: "electricity", he: "חשמל", emoji: null, tier: 39 },
  { en: "chemical", he: "כימיקל", emoji: null, tier: 39 },
  { en: "experiment", he: "ניסוי", emoji: "🧪", tier: 39 },
  { en: "planet", he: "כוכב לכת", emoji: "🪐", tier: 39 },
  { en: "galaxy", he: "גלקסיה", emoji: null, tier: 39 },
  { en: "atom", he: "אטום", emoji: null, tier: 39 },
  { en: "molecule", he: "מולקולה", emoji: null, tier: 39 },
  // tier 40
  { en: "intelligent", he: "אינטליגנטי", emoji: null, tier: 40 },
  { en: "creative", he: "יצירתי", emoji: null, tier: 40 },
  { en: "brave", he: "אמיץ", emoji: null, tier: 40 },
  { en: "honest", he: "כן", emoji: null, tier: 40 },
  { en: "lazy", he: "עצלן", emoji: null, tier: 40 },
  { en: "generous", he: "נדיב", emoji: null, tier: 40 },
  { en: "patient", he: "סבלני", emoji: null, tier: 40 },
  { en: "careful", he: "זהיר", emoji: null, tier: 40 },
  { en: "polite", he: "מנומס", emoji: null, tier: 40 },
  { en: "stubborn", he: "עקשן", emoji: null, tier: 40 },
  // tier 41
  { en: "mathematics", he: "מתמטיקה", emoji: null, tier: 41 },
  { en: "science", he: "מדע", emoji: "🔬", tier: 41 },
  { en: "history", he: "היסטוריה", emoji: null, tier: 41 },
  { en: "geography", he: "גאוגרפיה", emoji: null, tier: 41 },
  { en: "literature", he: "ספרות", emoji: null, tier: 41 },
  { en: "biology", he: "ביולוגיה", emoji: null, tier: 41 },
  { en: "chemistry", he: "כימיה", emoji: null, tier: 41 },
  { en: "physics", he: "פיזיקה", emoji: null, tier: 41 },
  { en: "art", he: "אמנות", emoji: "🎨", tier: 41 },
  { en: "grammar", he: "דקדוק", emoji: null, tier: 41 },
  // tier 42
  { en: "freedom", he: "חופש", emoji: null, tier: 42 },
  { en: "justice", he: "צדק", emoji: null, tier: 42 },
  { en: "courage", he: "אומץ", emoji: null, tier: 42 },
  { en: "honesty", he: "כנות", emoji: null, tier: 42 },
  { en: "loyalty", he: "נאמנות", emoji: null, tier: 42 },
  { en: "responsibility", he: "אחריות", emoji: null, tier: 42 },
  { en: "opportunity", he: "הזדמנות", emoji: null, tier: 42 },
  { en: "achievement", he: "הישג", emoji: null, tier: 42 },
  { en: "challenge", he: "אתגר", emoji: null, tier: 42 },
  { en: "ambition", he: "שאיפה", emoji: null, tier: 42 },
  // tier 43
  { en: "ancient", he: "עתיק", emoji: null, tier: 43 },
  { en: "modern", he: "מודרני", emoji: null, tier: 43 },
  { en: "mysterious", he: "מסתורי", emoji: null, tier: 43 },
  { en: "dangerous", he: "מסוכן", emoji: null, tier: 43 },
  { en: "peaceful", he: "שליו", emoji: null, tier: 43 },
  { en: "powerful", he: "עוצמתי", emoji: null, tier: 43 },
  { en: "fragile", he: "שביר", emoji: null, tier: 43 },
  { en: "flexible", he: "גמיש", emoji: null, tier: 43 },
  { en: "reliable", he: "אמין", emoji: null, tier: 43 },
  { en: "efficient", he: "יעיל", emoji: null, tier: 43 },
  // tier 44
  { en: "friendship", he: "חברות", emoji: null, tier: 44 },
  { en: "teamwork", he: "עבודת צוות", emoji: null, tier: 44 },
  { en: "leadership", he: "מנהיגות", emoji: null, tier: 44 },
  { en: "competition", he: "תחרות", emoji: null, tier: 44 },
  { en: "celebration", he: "חגיגה", emoji: "🎉", tier: 44 },
  { en: "tradition", he: "מסורת", emoji: null, tier: 44 },
  { en: "ceremony", he: "טקס", emoji: null, tier: 44 },
  { en: "festival", he: "פסטיבל", emoji: null, tier: 44 },
  { en: "holiday", he: "חג", emoji: null, tier: 44 },
  { en: "vacation", he: "חופשה", emoji: null, tier: 44 },
  // tier 45
  { en: "ecosystem", he: "מערכת אקולוגית", emoji: null, tier: 45 },
  { en: "environment", he: "סביבה", emoji: null, tier: 45 },
  { en: "pollution", he: "זיהום", emoji: null, tier: 45 },
  { en: "climate", he: "אקלים", emoji: null, tier: 45 },
  { en: "species", he: "מין", emoji: null, tier: 45 },
  { en: "habitat", he: "בית טבעי", emoji: null, tier: 45 },
  { en: "extinction", he: "הכחדה", emoji: null, tier: 45 },
  { en: "conservation", he: "שמירת טבע", emoji: null, tier: 45 },
  { en: "wildlife", he: "חיות בר", emoji: null, tier: 45 },
  { en: "biodiversity", he: "מגוון ביולוגי", emoji: null, tier: 45 },
  // tier 46
  { en: "perspective", he: "נקודת מבט", emoji: null, tier: 46 },
  { en: "argument", he: "טיעון", emoji: null, tier: 46 },
  { en: "evidence", he: "ראיה", emoji: null, tier: 46 },
  { en: "conclusion", he: "מסקנה", emoji: null, tier: 46 },
  { en: "theory", he: "תיאוריה", emoji: null, tier: 46 },
  { en: "hypothesis", he: "השערה", emoji: null, tier: 46 },
  { en: "analysis", he: "ניתוח", emoji: null, tier: 46 },
  { en: "summary", he: "סיכום", emoji: null, tier: 46 },
  { en: "opinion", he: "דעה", emoji: null, tier: 46 },
  { en: "fact", he: "עובדה", emoji: null, tier: 46 },
  // tier 47
  { en: "enormous", he: "עצום", emoji: null, tier: 47 },
  { en: "tiny", he: "זעיר", emoji: null, tier: 47 },
  { en: "exhausted", he: "מותש", emoji: null, tier: 47 },
  { en: "delighted", he: "מרוצה מאוד", emoji: null, tier: 47 },
  { en: "furious", he: "זועם", emoji: null, tier: 47 },
  { en: "terrified", he: "מבועת", emoji: null, tier: 47 },
  { en: "brilliant", he: "מבריק", emoji: null, tier: 47 },
  { en: "ridiculous", he: "מגוחך", emoji: null, tier: 47 },
  { en: "magnificent", he: "מפואר", emoji: null, tier: 47 },
  { en: "dreadful", he: "נורא", emoji: null, tier: 47 },
  // tier 48
  { en: "request", he: "בקשה", emoji: null, tier: 48 },
  { en: "permission", he: "רשות", emoji: null, tier: 48 },
  { en: "apologize", he: "להתנצל", emoji: null, tier: 48 },
  { en: "appreciate", he: "להעריך", emoji: null, tier: 48 },
  { en: "recommend", he: "להמליץ", emoji: null, tier: 48 },
  { en: "suggest", he: "להציע", emoji: null, tier: 48 },
  { en: "considerate", he: "מתחשב", emoji: null, tier: 48 },
  { en: "appropriate", he: "מתאים", emoji: null, tier: 48 },
  { en: "essential", he: "חיוני", emoji: null, tier: 48 },
  { en: "significant", he: "משמעותי", emoji: null, tier: 48 },
  // tier 49
  { en: "government", he: "ממשלה", emoji: null, tier: 49 },
  { en: "democracy", he: "דמוקרטיה", emoji: null, tier: 49 },
  { en: "election", he: "בחירות", emoji: null, tier: 49 },
  { en: "citizen", he: "אזרח", emoji: null, tier: 49 },
  { en: "law", he: "חוק", emoji: null, tier: 49 },
  { en: "rule", he: "כלל", emoji: null, tier: 49 },
  { en: "community", he: "קהילה", emoji: null, tier: 49 },
  { en: "society", he: "חברה", emoji: null, tier: 49 },
  { en: "economy", he: "כלכלה", emoji: null, tier: 49 },
  { en: "currency", he: "מטבע", emoji: null, tier: 49 },
  // tier 50
  { en: "author", he: "מחבר", emoji: null, tier: 50 },
  { en: "character", he: "דמות", emoji: null, tier: 50 },
  { en: "plot", he: "עלילה", emoji: null, tier: 50 },
  { en: "setting", he: "רקע העלילה", emoji: null, tier: 50 },
  { en: "theme", he: "נושא", emoji: null, tier: 50 },
  { en: "chapter", he: "פרק", emoji: null, tier: 50 },
  { en: "novel", he: "רומן", emoji: null, tier: 50 },
  { en: "poem", he: "שיר", emoji: null, tier: 50 },
  { en: "metaphor", he: "מטאפורה", emoji: null, tier: 50 },
  { en: "narrator", he: "מספר", emoji: null, tier: 50 },
  // tier 51
  { en: "independence", he: "עצמאות", emoji: null, tier: 51 },
  { en: "maturity", he: "בגרות", emoji: null, tier: 51 },
  { en: "identity", he: "זהות", emoji: null, tier: 51 },
  { en: "privacy", he: "פרטיות", emoji: null, tier: 51 },
  { en: "reputation", he: "מוניטין", emoji: null, tier: 51 },
  { en: "influence", he: "השפעה", emoji: null, tier: 51 },
  { en: "motivation", he: "מוטיבציה", emoji: null, tier: 51 },
  { en: "determination", he: "החלטיות", emoji: null, tier: 51 },
  { en: "perseverance", he: "התמדה", emoji: null, tier: 51 },
  { en: "resilience", he: "חוסן", emoji: null, tier: 51 },
  // tier 52
  { en: "negotiate", he: "לנהל משא ומתן", emoji: null, tier: 52 },
  { en: "compromise", he: "להתפשר", emoji: null, tier: 52 },
  { en: "cooperate", he: "לשתף פעולה", emoji: null, tier: 52 },
  { en: "collaborate", he: "לשתף פעולה יצירתי", emoji: null, tier: 52 },
  { en: "communicate", he: "לתקשר", emoji: null, tier: 52 },
  { en: "participate", he: "להשתתף", emoji: null, tier: 52 },
  { en: "contribute", he: "לתרום", emoji: null, tier: 52 },
  { en: "evaluate", he: "להעריך", emoji: null, tier: 52 },
  { en: "investigate", he: "לחקור", emoji: null, tier: 52 },
  { en: "demonstrate", he: "להדגים", emoji: null, tier: 52 },
  // tier 53
  { en: "empathy", he: "אמפתיה", emoji: null, tier: 53 },
  { en: "sympathy", he: "אהדה", emoji: null, tier: 53 },
  { en: "anxiety", he: "חרדה", emoji: null, tier: 53 },
  { en: "frustration", he: "תסכול", emoji: null, tier: 53 },
  { en: "enthusiasm", he: "התלהבות", emoji: null, tier: 53 },
  { en: "contentment", he: "שביעות רצון", emoji: null, tier: 53 },
  { en: "resentment", he: "טינה", emoji: null, tier: 53 },
  { en: "admiration", he: "הערכה רבה", emoji: null, tier: 53 },
  { en: "gratitude", he: "הכרת תודה", emoji: null, tier: 53 },
  { en: "indifference", he: "אדישות", emoji: null, tier: 53 },
  // tier 54
  { en: "organism", he: "אורגניזם", emoji: null, tier: 54 },
  { en: "cell", he: "תא", emoji: null, tier: 54 },
  { en: "evolution", he: "אבולוציה", emoji: null, tier: 54 },
  { en: "bacteria", he: "חיידקים", emoji: null, tier: 54 },
  { en: "virus", he: "נגיף", emoji: null, tier: 54 },
  { en: "vaccine", he: "חיסון", emoji: null, tier: 54 },
  { en: "nutrient", he: "רכיב תזונתי", emoji: null, tier: 54 },
  { en: "photosynthesis", he: "פוטוסינתזה", emoji: null, tier: 54 },
  { en: "metabolism", he: "חילוף חומרים", emoji: null, tier: 54 },
  { en: "gene", he: "גן", emoji: null, tier: 54 },
  // tier 55
  { en: "heritage", he: "מורשת", emoji: null, tier: 55 },
  { en: "immigrant", he: "מהגר", emoji: null, tier: 55 },
  { en: "diversity", he: "גיוון", emoji: null, tier: 55 },
  { en: "custom", he: "מנהג", emoji: null, tier: 55 },
  { en: "religion", he: "דת", emoji: null, tier: 55 },
  { en: "ritual", he: "ריטואל", emoji: null, tier: 55 },
  { en: "civilization", he: "תרבות אנושית", emoji: null, tier: 55 },
  { en: "migration", he: "נדידה", emoji: null, tier: 55 },
  { en: "globalization", he: "גלובליזציה", emoji: null, tier: 55 },
  { en: "multicultural", he: "רב-תרבותי", emoji: null, tier: 55 },
  // tier 56
  { en: "philosophy", he: "פילוסופיה", emoji: null, tier: 56 },
  { en: "psychology", he: "פסיכולוגיה", emoji: null, tier: 56 },
  { en: "sociology", he: "סוציולוגיה", emoji: null, tier: 56 },
  { en: "economics", he: "מדעי הכלכלה", emoji: null, tier: 56 },
  { en: "statistics", he: "סטטיסטיקה", emoji: null, tier: 56 },
  { en: "algorithm", he: "אלגוריתם", emoji: null, tier: 56 },
  { en: "variable", he: "משתנה", emoji: null, tier: 56 },
  { en: "equation", he: "משוואה", emoji: null, tier: 56 },
  { en: "coefficient", he: "מקדם", emoji: null, tier: 56 },
  { en: "theorem", he: "משפט מתמטי", emoji: null, tier: 56 },
  // tier 57
  { en: "ambiguous", he: "מעורפל", emoji: null, tier: 57 },
  { en: "arbitrary", he: "שרירותי", emoji: null, tier: 57 },
  { en: "coherent", he: "קוהרנטי", emoji: null, tier: 57 },
  { en: "controversial", he: "שנוי במחלוקת", emoji: null, tier: 57 },
  { en: "inevitable", he: "בלתי נמנע", emoji: null, tier: 57 },
  { en: "legitimate", he: "לגיטימי", emoji: null, tier: 57 },
  { en: "plausible", he: "סביר", emoji: null, tier: 57 },
  { en: "subtle", he: "עדין / דק", emoji: null, tier: 57 },
  { en: "versatile", he: "רב-תכליתי", emoji: null, tier: 57 },
  { en: "meticulous", he: "קפדני", emoji: null, tier: 57 },
  // tier 58
  { en: "consciousness", he: "מודעות", emoji: null, tier: 58 },
  { en: "morality", he: "מוסריות", emoji: null, tier: 58 },
  { en: "existence", he: "קיום", emoji: null, tier: 58 },
  { en: "perception", he: "תפיסה", emoji: null, tier: 58 },
  { en: "cognition", he: "קוגניציה", emoji: null, tier: 58 },
  { en: "intuition", he: "אינטואיציה", emoji: null, tier: 58 },
  { en: "rationality", he: "רציונליות", emoji: null, tier: 58 },
  { en: "subjectivity", he: "סובייקטיביות", emoji: null, tier: 58 },
  { en: "objectivity", he: "אובייקטיביות", emoji: null, tier: 58 },
  { en: "paradox", he: "פרדוקס", emoji: null, tier: 58 },
  // tier 59
  { en: "contemplate", he: "להתבונן במחשבה", emoji: null, tier: 59 },
  { en: "articulate", he: "לבטא בבהירות", emoji: null, tier: 59 },
  { en: "differentiate", he: "להבחין", emoji: null, tier: 59 },
  { en: "substantiate", he: "לבסס בראיות", emoji: null, tier: 59 },
  { en: "undermine", he: "לחתור תחת", emoji: null, tier: 59 },
  { en: "alleviate", he: "להקל", emoji: null, tier: 59 },
  { en: "exacerbate", he: "להחמיר", emoji: null, tier: 59 },
  { en: "facilitate", he: "להקל / לאפשר", emoji: null, tier: 59 },
  { en: "mitigate", he: "לרכך", emoji: null, tier: 59 },
  { en: "perpetuate", he: "להנציח", emoji: null, tier: 59 },
  // tier 60
  { en: "procrastination", he: "דחיינות", emoji: null, tier: 60 },
  { en: "perfectionism", he: "פרפקציוניזם", emoji: null, tier: 60 },
  { en: "introspection", he: "התבוננות עצמית", emoji: null, tier: 60 },
  { en: "authenticity", he: "אותנטיות", emoji: null, tier: 60 },
  { en: "vulnerability", he: "פגיעות", emoji: null, tier: 60 },
  { en: "mindfulness", he: "מיינדפולנס", emoji: null, tier: 60 },
  { en: "altruism", he: "אלטרואיזם", emoji: null, tier: 60 },
  { en: "pragmatism", he: "פרגמטיזם", emoji: null, tier: 60 },
  { en: "skepticism", he: "ספקנות", emoji: null, tier: 60 },
  { en: "nostalgia", he: "נוסטלגיה", emoji: null, tier: 60 },
];
