// English word -> Hebrew translation, with an emoji for a non-reading visual cue,
// and a difficulty tier (1 = easiest) used to grow the word pool as a kid levels up.
window.WORDS = [
  { en: "apple", he: "תפוח", emoji: "🍎", difficulty: 1 },
  { en: "banana", he: "בננה", emoji: "🍌", difficulty: 2 },
  { en: "orange", he: "תפוז", emoji: "🍊", difficulty: 2 },
  { en: "grapes", he: "ענבים", emoji: "🍇", difficulty: 2 },
  { en: "watermelon", he: "אבטיח", emoji: "🍉", difficulty: 3 },
  { en: "strawberry", he: "תות", emoji: "🍓", difficulty: 3 },
  { en: "carrot", he: "גזר", emoji: "🥕", difficulty: 2 },
  { en: "bread", he: "לחם", emoji: "🍞", difficulty: 2 },
  { en: "cheese", he: "גבינה", emoji: "🧀", difficulty: 2 },
  { en: "pizza", he: "פיצה", emoji: "🍕", difficulty: 2 },
  { en: "ice cream", he: "גלידה", emoji: "🍦", difficulty: 3 },
  { en: "cake", he: "עוגה", emoji: "🎂", difficulty: 1 },
  { en: "dog", he: "כלב", emoji: "🐶", difficulty: 1 },
  { en: "cat", he: "חתול", emoji: "🐱", difficulty: 1 },
  { en: "lion", he: "אריה", emoji: "🦁", difficulty: 2 },
  { en: "elephant", he: "פיל", emoji: "🐘", difficulty: 3 },
  { en: "monkey", he: "קוף", emoji: "🐵", difficulty: 2 },
  { en: "fish", he: "דג", emoji: "🐟", difficulty: 1 },
  { en: "bird", he: "ציפור", emoji: "🐦", difficulty: 1 },
  { en: "rabbit", he: "ארנב", emoji: "🐰", difficulty: 2 },
  { en: "horse", he: "סוס", emoji: "🐴", difficulty: 2 },
  { en: "cow", he: "פרה", emoji: "🐮", difficulty: 1 },
  { en: "sun", he: "שמש", emoji: "☀️", difficulty: 1 },
  { en: "moon", he: "ירח", emoji: "🌙", difficulty: 1 },
  { en: "star", he: "כוכב", emoji: "⭐", difficulty: 1 },
  { en: "rain", he: "גשם", emoji: "🌧️", difficulty: 2 },
  { en: "tree", he: "עץ", emoji: "🌳", difficulty: 1 },
  { en: "flower", he: "פרח", emoji: "🌸", difficulty: 2 },
  { en: "house", he: "בית", emoji: "🏠", difficulty: 1 },
  { en: "car", he: "מכונית", emoji: "🚗", difficulty: 1 },
  { en: "bicycle", he: "אופניים", emoji: "🚲", difficulty: 3 },
  { en: "airplane", he: "מטוס", emoji: "✈️", difficulty: 3 },
  { en: "boat", he: "סירה", emoji: "⛵", difficulty: 2 },
  { en: "ball", he: "כדור", emoji: "⚽", difficulty: 1 },
  { en: "book", he: "ספר", emoji: "📖", difficulty: 1 },
  { en: "school", he: "בית ספר", emoji: "🏫", difficulty: 3 },
  { en: "chair", he: "כיסא", emoji: "🪑", difficulty: 2 },
  { en: "table", he: "שולחן", emoji: "🛋️", difficulty: 2 },
  { en: "clock", he: "שעון", emoji: "🕐", difficulty: 2 },
  { en: "key", he: "מפתח", emoji: "🔑", difficulty: 1 },
  { en: "hat", he: "כובע", emoji: "🎩", difficulty: 1 },
  { en: "shoe", he: "נעל", emoji: "👟", difficulty: 2 },
  { en: "shirt", he: "חולצה", emoji: "👕", difficulty: 2 },
  { en: "umbrella", he: "מטריה", emoji: "☂️", difficulty: 3 },
  { en: "balloon", he: "בלון", emoji: "🎈", difficulty: 3 },
  { en: "one", he: "אחד", emoji: "1️⃣", difficulty: 1 },
  { en: "two", he: "שתיים", emoji: "2️⃣", difficulty: 1 },
  { en: "three", he: "שלוש", emoji: "3️⃣", difficulty: 1 },
  { en: "red", he: "אדום", emoji: "🔴", difficulty: 1 },
  { en: "blue", he: "כחול", emoji: "🔵", difficulty: 1 },
  { en: "yellow", he: "צהוב", emoji: "🟡", difficulty: 2 },
  { en: "green", he: "ירוק", emoji: "🟢", difficulty: 2 },
  { en: "mom", he: "אמא", emoji: "👩", difficulty: 1 },
  { en: "dad", he: "אבא", emoji: "👨", difficulty: 1 },
  { en: "baby", he: "תינוק", emoji: "👶", difficulty: 1 },
  { en: "friend", he: "חבר", emoji: "🧒", difficulty: 2 },
];
